version: 1
update_configs:
  - package_manager: "python"
    directory: "/requirements"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "Django"
          version_requirement: ">=3.0"
      - match:
          # billiard is required by celery, pinned to <3.6 until we upgrade Celery to a version that
          # supports it.
          dependency_name: "billiard"
          version_requirement: ">=4.0"
      - match:
          dependency_name: "django-tables2"
          version_requirement: ">=2"
      - match:
          dependency_name: "elasticsearch"
          version_requirement: ">=6"
      - match:
          dependency_name: "elasticsearch-dsl"
          version_requirement: ">=6"
      - match:
          dependency_name: "pygit2"
          version_requirement: ">=1.2.0"
